
DROP TABLE actor IF EXISTS;

/*
 *  TABLE: DEMO.ACTOR
 */

CREATE TABLE DEMO.ACTOR
(
  ACTOR_ID           INTEGER            NOT NULL  AUTO_INCREMENT,
  USERNAME           VARCHAR2(255)      NOT NULL,
  RESOURCES_REQUESTED INTEGER           NOT NULL,
  RECORD_VERSION     INTEGER            NOT NULL,
  CREATED_BY         VARCHAR2(30)       NOT NULL,
  CREATED_TIMESTAMP  DATETIME           NOT NULL,
  UPDATED_BY         VARCHAR2(30),
  UPDATED_TIMESTAMP  DATETIME,
);

ALTER TABLE DEMO.ACTOR ADD
  CONSTRAINT ACTOR_PK
  PRIMARY KEY (ACTOR_ID)
;

ALTER TABLE DEMO.ACTOR ADD
  CONSTRAINT ACTOR_USERNAME_U1
  UNIQUE (USERNAME)
;