INSERT INTO DEMO.ACTOR (ACTOR_ID, USERNAME, RESOURCES_REQUESTED, RECORD_VERSION, CREATED_BY, CREATED_TIMESTAMP) VALUES(1, 'jsmith', 0, 0, 'data-init', SYSDATE);
INSERT INTO DEMO.ACTOR (ACTOR_ID, USERNAME, RESOURCES_REQUESTED, RECORD_VERSION, CREATED_BY, CREATED_TIMESTAMP) VALUES(2, 'jdoe', 0, 0, 'data-init', SYSDATE);


-- INSERT INTO DEMO.ACTOR (
--   ACTOR_ID,
--   USERNAME,
--   RESOURCES_REQUESTED,
--   RECORD_VERSION,
--   CREATED_BY,
--   CREATED_TIMESTAMP
-- ) VALUES (
--   1,
--   'jsmith',
--   0,
--   0,
--   'UnitTest',
--   SYSDATE
-- );
--
-- INSERT INTO DEMO.ACTOR (
--   ACTOR_ID,
--   USERNAME,
--   RESOURCES_REQUESTED,
--   RECORD_VERSION,
--   CREATED_BY,
--   CREATED_TIMESTAMP
-- ) VALUES (
--   2,
--   'jdoe',
--   0,
--   0,
--   'UnitTest',
--   SYSDATE
-- );
